<?php /** @var Vianetz_CheckoutAttributes_Block_Sales_Order $this */ ?>
<div class="col-set order-info-box">
    <div class="col">
        <div class="box">
            <div class="box-content">
                <?php $custom = $this->getCustomVars(); ?>
                <?php foreach ($custom as $key => $value): ?>
                    <b><?php echo $this->__($key);?></b> : <?php echo $value; ?> <br/>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>