<?php /** @var Vianetz_CheckoutAttributes_Block_Sales_Order $this */ ?>
<?php $_order = $this->getOrder() ?>
<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo $this->__('Custom Fields') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php foreach ($this->getCustomVars() as $key => $value): ?>
                    <tr>
                        <td style="width:10%" class="label">
                            <strong><?php echo $this->__($key) ?></strong>
                        </td>
                        <td class="value"><?php echo $value;?></td>
                    </tr>
                    <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
<div class="clear"></div>